name: Release Prod
on:
  repository_dispatch:
    types: [deploy_prod]

  workflow_dispatch:
    inputs:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    if: github.actor == github.event.repository.owner.login

    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Release
        run: |
          PWD="$(pwd)"
          mkdir -p ~/.gradle
          touch ~/.gradle/gradle.properties
          RELEASE_JSON_FILE="${PWD}/play-store.json"
          echo "${{ secrets.ANDFHEMPLAYUPLOADRELEASEBASE64JSON }}" | base64 --decode > "${RELEASE_JSON_FILE}"

          echo "andFHEMReleaseStorePassword=${{ secrets.andFHEMReleaseStorePassword }}" >> ~/.gradle/gradle.properties
          echo "andFHEMReleaseAliasPassword=${{ secrets.andFHEMReleaseAliasPassword }}" >> ~/.gradle/gradle.properties
          echo "andFHEMGithubToken=${{ secrets.andFHEMGithubToken }}" >> ~/.gradle/gradle.properties
          echo "andFHEMReleaseAccount=${{ secrets.andFHEMReleaseAccount }}" >> ~/.gradle/gradle.properties
          echo "andFHEMPlayServiceAccountCredentials=${RELEASE_JSON_FILE}" >> ~/.gradle/gradle.properties

          git config user.email "andFHEM@klass.i"
          git config user.name "AndFHEM"
          ./gradlew clean release -Dstage=production
